name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Configure (CMake)
        env:
          CC: ${{ matrix.compiler }}
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: |
          cmake --build build

      - name: Pipe Benchmark
        run: |
          if [ -x ./bin/pipe_bw ]; then
            ./bin/pipe_bw --max-bytes=1MiB
          fi
      - name: Message Queue Benchmark
        run: |
          if [ -x ./bin/mq_bw ]; then
            ./bin/mq_bw --max-bytes=1MiB || true
          fi
      - name: Shared Memory Benchmark
        run: |
          if [ -x ./bin/shm_mem ]; then
            ./bin/shm_mem --min-bytes=1 --max-bytes=100MiB --reader_core=0 --writer_core=1 --is_writer=1 || true
          fi
